### PR TITLE
Landing page

### LINKED ISSUE #15: Create a web site for the project
- Project goal
- Team members
- GitHub repository link, tools using/used
- Screenshorts and videos
- Link to Kitware, LANL, and LBNL, ATS, VTK, CMB, and ParaView

### PR DESCRIPTION
**Pull request by jtomeck**
Work in progress currently, but making progress on the landing page. Feel free to make any preliminary reviews and see if the editing approach makes sense.

Resolve #15

### CODE REVIEW

**Comment by banesullivan** [comment]
Looking great so far, @jtomeck - Thanks! Let me know when you're ready for me to fill in a bit more content that you don't have.

Otherwise, the layout, colors, organization, and all that jazz look excellent

**Comment by jtomeck** [comment]
@banesullivan - The homepage is all set for real content and links. I'll work on the interior page template tomorrow, I'm sorry I didn't have time today. It will hopefully be relatively quick to accomplish, and there should already be SOME form of interior page already created with the template we're using. Just creating a page and setting `layout: page` in the frontmatter should do it. You should also add `permalink: /page-name/` to avoid having "url.com/page-name.html."

Let me know if you have any questions! Also, should I mark this ready for review, or keep it a draft?

**Comment by banesullivan** [comment]
> The homepage is all set for real content and links.

Awesome work! I just filled in the missing content for the homepage

> I'll work on the interior page template tomorrow, I'm sorry I didn't have time today. It will hopefully be relatively quick to accomplish, and there should already be SOME form of interior page already created with the template we're using. Just creating a page and setting layout: page in the frontmatter should do it. You should also add permalink: /page-name/ to avoid having "url.com/page-name.html."

Thanks, Jared! No immediate rush on this - I'll wait until your wrapped up to add anything else

> Let me know if you have any questions! Also, should I mark this ready for review, or keep it a draft?

Either way is fine - PR status/reviews in the repo are pretty lax

**Comment by jtomeck** [comment]
@banesullivan - I've pushed a bunch more commits. You should be able to create any additional pages and fix/update content on what I've done. Give it a review and see if anything else is needed!

I did have one question about the contact page. Will this nav item link back to an existing contact form somewhere, or do we want to build a form directly on the site?

**Comment by banesullivan** [comment]
So far, this is looking great and I think I can handle the rest of the content. For the contact form, we do not have an official line of contact about the project. Perhaps just a `mailto:` link to one of the team members? Thoughts, @aashish24?

**Comment by banesullivan** [comment]
> For the contact form, we do not have an official line of contact about the project. Perhaps just a mailto: link

This should be a `mailto:` link to `kitware@kitware.com`

**Pull request merged**
